"use client";

import React, { useState, useEffect } from "react";
import { SemanticContentAnalyzer } from "./_components/extension-algorithm";
import { Chrome, Search, Link as LinkIcon, BookOpen, Puzzle, ArrowRightCircle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function BrowserExtensionPage() {
  const [analyzer, setAnalyzer] = useState(null);
  const [activeTabContent, setActiveTabContent] = useState("");
  const [tooltips, setTooltips] = useState([]);
  const [isScanning, setIsScanning] = useState(false);

  const userCurriculum = [
      { id: "mod_1", name: "Intro to Containerization", status: "active", tags: ["containerization", "devops"] },
      { id: "mod_2", name: "Persistent Storage Architecture", status: "recommended", tags: ["storage", "persistence", "database"] },
      { id: "mod_3", name: "Advanced React Patterns", status: "locked", tags: ["frontend", "components"] } // Locked modules shouldn't trigger
  ];

  useEffect(() => {
      setAnalyzer(new SemanticContentAnalyzer(userCurriculum));
      
      // Default mock text representing a 3rd party docs site
      setActiveTabContent(`
# Docker Storage Basics
When working with Docker, data inside a container is ephemeral.
If the container goes down, the data is lost.
To solve this, you should use a Volume. 
Volumes are the preferred mechanism for persisting data generated by and used by containers.
      `);
  }, []);

  const handleScanText = () => {
      if (!analyzer) return;
      setIsScanning(true);
      setTooltips([]);

      setTimeout(() => {
          const matches = analyzer.analyzeDOMText(activeTabContent);
          const generatedTooltips = matches.map(m => analyzer.generateTooltipPayload(m));
          setTooltips(generatedTooltips);
          setIsScanning(false);
      }, 600);
  };

  const getHighlightedText = (text) => {
      if (tooltips.length === 0) return text;

      // Simple mock highlighting logic for demo purposes
      let highlighted = text;
      const highlightWords = ["Docker", "Volume", "Volumes", "persisting"];
      
      highlightWords.forEach(word => {
          const regex = new RegExp(`(${word})`, 'gi');
          highlighted = highlighted.replace(regex, '<span class="bg-blue-500/30 border-b-2 border-blue-500 text-blue-200 cursor-help transition-colors hover:bg-blue-500/50">$1</span>');
      });

      return <div dangerouslySetInnerHTML={{ __html: highlighted }} />;
  };

  return (
    <div className="container mx-auto p-6 max-w-6xl space-y-8 animate-in fade-in zoom-in duration-500">
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h1 className="text-4xl font-extrabold tracking-tight flex items-center gap-3">
            <Puzzle className="w-10 h-10 text-blue-500" />
            Context-Aware Browser Extension
          </h1>
          <p className="text-muted-foreground mt-2 text-lg">
            Inject semantic, Just-in-Time learning tooltips into third-party documentation.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <Card className="border-blue-500/20 shadow-lg shadow-blue-500/5 overflow-hidden">
            <CardHeader className="bg-gray-100 dark:bg-gray-900 border-b flex flex-row items-center justify-between py-3">
              <div className="flex items-center gap-2 text-muted-foreground">
                  <div className="flex gap-1.5 mr-4">
                      <div className="w-3 h-3 rounded-full bg-red-500"></div>
                      <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                      <div className="w-3 h-3 rounded-full bg-green-500"></div>
                  </div>
                  <Chrome className="w-4 h-4" />
                  <span className="text-xs font-mono bg-background px-3 py-1 rounded border">docs.docker.com/storage/volumes/</span>
              </div>
              <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={handleScanText} disabled={isScanning} className="h-7 text-xs bg-blue-500/10 border-blue-500/30 text-blue-500 hover:bg-blue-500 hover:text-white">
                      {isScanning ? <Search className="w-3 h-3 animate-spin mr-1" /> : <Puzzle className="w-3 h-3 mr-1" />}
                      Scan DOM
                  </Button>
              </div>
            </CardHeader>
            <CardContent className="p-0 relative bg-white dark:bg-[#121212] min-h-[400px]">
                {/* Simulated 3rd Party Webpage */}
                <div className="p-8 font-sans text-lg leading-relaxed text-gray-800 dark:text-gray-300">
                    <textarea 
                        className="w-full h-32 bg-transparent resize-none border-none focus:outline-none hidden" 
                        value={activeTabContent}
                        onChange={(e) => setActiveTabContent(e.target.value)}
                    />
                    
                    {tooltips.length > 0 ? (
                        <div className="whitespace-pre-wrap">
                            {getHighlightedText(activeTabContent)}
                        </div>
                    ) : (
                        <div className="whitespace-pre-wrap">
                            {activeTabContent}
                        </div>
                    )}
                </div>

                {/* Simulated Extension Tooltip Injection */}
                {tooltips.length > 0 && (
                    <div className="absolute top-32 left-1/3 bg-background border shadow-2xl rounded-xl p-4 w-72 animate-in zoom-in-95 duration-200 z-50 pointer-events-none">
                        <div className="flex items-center gap-2 text-blue-500 mb-2 border-b pb-2">
                            <Puzzle className="w-4 h-4" />
                            <span className="font-bold text-sm">Pathfinder Link Found</span>
                        </div>
                        <h4 className="font-semibold text-sm mb-1">{tooltips[0]?.title}</h4>
                        <p className="text-xs text-muted-foreground mb-3">{tooltips[0]?.description}</p>
                        <div className="flex gap-1 mb-3">
                            {tooltips[0]?.tags.map(t => <span key={t} className="text-[10px] bg-secondary px-2 py-0.5 rounded-full">{t}</span>)}
                        </div>
                        <Button size="sm" className="w-full text-xs h-7 bg-blue-600 hover:bg-blue-700 pointer-events-auto">
                            Resume Module <ArrowRightCircle className="w-3 h-3 ml-1" />
                        </Button>
                    </div>
                )}
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
            <Card className="h-full border-dashed">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <BookOpen className="w-5 h-5" />
                        User Curriculum
                    </CardTitle>
                    <CardDescription>Extension internal state</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    {userCurriculum.map(mod => (
                        <div key={mod.id} className={`p-3 rounded-lg border ${mod.status === 'active' ? 'bg-blue-500/10 border-blue-500/30' : mod.status === 'recommended' ? 'bg-green-500/10 border-green-500/30' : 'bg-muted/30 border-dashed opacity-50'}`}>
                            <div className="flex justify-between items-center mb-1">
                                <h4 className="font-bold text-sm">{mod.name}</h4>
                                <span className={`text-[10px] uppercase font-bold px-1.5 rounded ${mod.status === 'active' ? 'bg-blue-500 text-white' : mod.status === 'recommended' ? 'bg-green-500 text-white' : 'bg-muted-foreground text-background'}`}>
                                    {mod.status}
                                </span>
                            </div>
                            <div className="flex flex-wrap gap-1 mt-2">
                                {mod.tags.map(t => <span key={t} className="text-[10px] bg-background border px-1.5 rounded text-muted-foreground">{t}</span>)}
                            </div>
                        </div>
                    ))}

                    <div className="mt-8 p-4 bg-secondary/50 rounded-xl">
                        <h4 className="font-semibold text-sm flex items-center gap-2 mb-2">
                            <LinkIcon className="w-4 h-4" /> Semantic Mapping
                        </h4>
                        <p className="text-xs text-muted-foreground leading-relaxed">
                            The extension background script continuously parses the active DOM for keywords (like "Volume" or "Docker"), mapping them to abstract concepts (like "storage" or "containerization"), and correlating them with the tags in your active Pathfinder curriculum to generate Just-in-Time links.
                        </p>
                    </div>
                </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
